### ISSUE TITLE
Movielens 20m

### ISSUE THREAD

**Issue by SandroLuck** [changun/CollMetric#9]
I was trying to reproduce the results you had with Movielens20m.
I failed to reproduce them and assume it's cause of the way the dataset is filtered.

While I was able to reproduce the recall mention in the paper for movielens100k.

Could you let us know a bit more about your filtering of the Movielens20m dataset?
If you still have the dataset I would be extremely greatful if you could make it available such that I can compare my results better to yours.
I could bind it into the algorithm myself

**Comment by changun** [comment]
Hi Sandro,

I am very sorry for my late reply. I didn't saw this issue until I got the
notification of the latest issue. Do you still need help reproduce the
MovieLens results? Which scenario in the paper you try to reproduce (with
features or without)?

**Comment by changun** [comment]
I am closing this issue. feel free to reopen it if you have any further questions.

**Comment by SandroLuck** [comment]
Sorry for the late reply. I was not able to recreate it but switched to other datasets which I had more data for
